# Generated by Django 4.2 on 2023-09-02 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_inventory_product_alter_orderline_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.product', to_field='product_code'),
        ),
    ]
