# Generated by Django 4.2 on 2023-09-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_orderline_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('inventory', models.IntegerField()),
                ('orderpoint', models.IntegerField()),
                ('product_code', models.CharField(max_length=20)),
                ('product_name', models.CharField(max_length=100)),
            ],
        ),
    ]
